### 글 작성

POST http://localhost:8080/api/v1/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRlc3QwMSIsImlhdCI6MTc0MTIzODY2NCwiZXhwIjoxNzQzODMwNjY0LCJzdWIiOiJ0ZXN0MDEifQ.rSGNtfihFgSAUD5sAe4Bh9K0iFLl_wDfuSBjqgO3H9I

{
  "title": "title1",
  "body": "this is body1"
}

### 글 수정

PUT http://localhost:8080/api/v1/posts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRlc3QwMSIsImlhdCI6MTc0MTI0NTk5MCwiZXhwIjoxNzQzODM3OTkwLCJzdWIiOiJ0ZXN0MDEifQ.ULzPjfbG1Oq8J7zSivzVS40X4Lq92KEU5ck8piSxSzM

{
"title": "title1 modify",
"body": "this is body1 modify"
}

### 글 삭제

DELETE http://localhost:8080/api/v1/posts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRlc3QwMSIsImlhdCI6MTc0MTI0NTk5MCwiZXhwIjoxNzQzODM3OTkwLCJzdWIiOiJ0ZXN0MDEifQ.ULzPjfbG1Oq8J7zSivzVS40X4Lq92KEU5ck8piSxSzM

### 전체 글 조회
GET http://localhost:8080/api/v1/posts?size=10&page=0&sort=id
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRlc3QwMiIsImlhdCI6MTc0MTMwNjQwMywiZXhwIjoxNzQzODk4NDAzLCJzdWIiOiJ0ZXN0MDIifQ.KmNhYTSwXJfrKkA42HlojhQNdt3TLIcymNMsWPi7PjI

### 나의 전체 글 조회
GET http://localhost:8080/api/v1/posts/my?size=10&page=0&sort=id
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRlc3QwMSIsImlhdCI6MTc0MTMwNjQ2NywiZXhwIjoxNzQzODk4NDY3LCJzdWIiOiJ0ZXN0MDEifQ.3R6hlYw3--OwjEzpZo5saLed6POL2WGu0PHI-TWdLTc