### 글 작성

POST http://localhost:8080/api/v1/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NDIzMDQyNjQsImV4cCI6MTc0NDg5NjI2NH0.FIwHOqFiuYdFs1Zt0I3_-LSREgWRx8_wNWKwN1_2b70

{
  "title": "title1",
  "body": "this is body1"
}

### 글 수정

PUT http://localhost:8080/api/v1/posts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NDIzMDQyNjQsImV4cCI6MTc0NDg5NjI2NH0.FIwHOqFiuYdFs1Zt0I3_-LSREgWRx8_wNWKwN1_2b70

{
"title": "title1 modify",
"body": "this is body1 modify"
}

### 글 삭제

DELETE http://localhost:8080/api/v1/posts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NDIzMDQyNjQsImV4cCI6MTc0NDg5NjI2NH0.FIwHOqFiuYdFs1Zt0I3_-LSREgWRx8_wNWKwN1_2b70

### 전체 글 조회
GET http://localhost:8080/api/v1/posts?size=10&page=0&sort=id
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NDIzMDQyNjQsImV4cCI6MTc0NDg5NjI2NH0.FIwHOqFiuYdFs1Zt0I3_-LSREgWRx8_wNWKwN1_2b70

### 나의 전체 글 조회
GET http://localhost:8080/api/v1/posts/my?size=10&page=0&sort=id
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NDIzMDQyNjQsImV4cCI6MTc0NDg5NjI2NH0.FIwHOqFiuYdFs1Zt0I3_-LSREgWRx8_wNWKwN1_2b70